// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwjdnauqugpdagkhzmef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13amRuYXVxdWdwZGFna2h6bWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjI4NDcsImV4cCI6MjA2MDA5ODg0N30.lWDKrcq6kfnn030gAqnEU5jp6JhHE4vkGvg6KcO4w1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);